services:
  backend:
    build: ./backend
    container_name: ww_backend_c
    ports:
      - 4000:4000
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    environment:
      - DATABASE_URL=postgresql://ww_admin:ww_password@database:5432/ww_db
      - REDIS_URL=redis://redis:6379
      - OLLAMA_HOST=http://host.docker.internal:11434
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build: ./frontend
    container_name: ww_frontend_c
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend

  database:
    image: pgvector/pgvector:pg15
    container_name: postgres-db
    environment:
      - POSTGRES_DB=ww_db
      - POSTGRES_USER=ww_admin
      - POSTGRES_PASSWORD=ww_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ww_admin -d ww_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ww_postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: ww_redis_c
    ports:
      - "6379:6379"

volumes:
  ww_postgres_data:
